### ISSUE TITLE
4. Personas

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Wiki#10]
Describe personas for your problem. **must use the template provided by the course**

**Comment by Crola1702** [comment]
From #6 

All personas need to be checked and revised
![image](https://github.com/ISIS3510-202320-Team13/Wiki/assets/71995657/c82d5bd1-cc63-4f63-baac-2b239df566df)
Specially this one that has weird lines and its incorrectly classified
