### ISSUE TITLE
5. Empathy Maps

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Wiki#11]
Describe empathy maps for your problem. You must include an answer for the Thinks, Sees, Feels and Does sections relating each answer to the problems that were chosen

**Comment by Crola1702** [comment]
From  #5 

![image](https://github.com/ISIS3510-202320-Team13/Wiki/assets/71995657/b50f83eb-09c9-4004-ace9-b14ff8ad8b02)
The map has a says category, it should be sees
![image](https://github.com/ISIS3510-202320-Team13/Wiki/assets/71995657/f3df4a15-b5dc-4c66-bbb4-2a2684ff8f17)
This persona is necessary?

**Comment by jcacerescc** [comment]
#5
