### ISSUE TITLE
7. Business Questions

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Wiki#12]
Provide a total of 14 business questions using the following restrictions.
a. At least 2 type 1 questions
b. At least 4 type 2 questions
c. At least 4 type 3 questions
d. At least 2 type 4 questions
e. At least 2 type 5 questions

**Comment by jcacerescc** [comment]
Apply this corrections
![image](https://github.com/ISIS3510-202320-Team13/Wiki/assets/89409633/f6b5f27f-0150-42f5-a39c-9d0c4e84d793)

**Comment by JuanLugoS** [comment]
add another type 5
