### ISSUE TITLE
8. VD Map

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Wiki#13]
Provide a VD Map for your solution. The VD Map must display all 14 business questions, and the data sources used on it must be obtainable through the designed solution or are publicly available. This task will also be graded considering the quality of the provided business questions

**Comment by JuanLugoS** [comment]
Modify based on changes of business questions Draft #12

**Comment by JuanReyes01** [comment]
Also revise the bussines questions on the VD map

**Comment by jcacerescc** [comment]
#12
