### ISSUE TITLE
10. Functional scenarios

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Wiki#14]
Provide 12 functional scenarios for your solution. These scenarios are described using the book’s framework (user action, system response and execution context).

**Comment by JuanReyes01** [comment]
Each one does 2 FS @nFei @JuanLugoS @Crola1702 @sepenuela @JuanReyes01 @jcacerescc

**Comment by Crola1702** [comment]
- [x] Cristobal

**Comment by jcacerescc** [comment]
Done

**Comment by sepenuela** [comment]
Done
