### ISSUE TITLE
11. Quality scenarios

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Wiki#15]
Provide 12 quality scenarios for your solution. These scenarios are described with the book’s framework in mind (scenario name, quality attributes, app status and context, changes in the context and system reaction).

**Comment by JuanReyes01** [comment]
Each one does 2 QS @nFei @JuanLugoS @Crola1702 @sepenuela @jcacerescc

**Comment by Crola1702** [comment]
- [x] Cristobal

**Comment by jcacerescc** [comment]
Done

**Comment by sepenuela** [comment]
Done
