### ISSUE TITLE
15. Individual Process Competences

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Wiki#17]
1. Deliver written artifacts that are: readable, understandable, are consistent in terms of presentation format and in general are top-notch products. These points will be graded considering the completeness of the tasks.
2. Use the existing repository tools (i.e., Milestones, issues, squash and merge request/approval, Kanban board, verbose commits).

**Comment by JuanReyes01** [comment]
Take into account this issue in all the tasks @nFei @JuanLugoS @Crola1702 @sepenuela @JuanReyes01 @jcacerescc
