### ISSUE TITLE
Revision of empathy maps before final delivery

### ISSUE THREAD

**Issue by JuanReyes01** [ISIS3510-202320-Team13/Wiki#5]
![image](https://github.com/ISIS3510-202320-Team13/Wiki/assets/71995657/b50f83eb-09c9-4004-ace9-b14ff8ad8b02)
The map has a says category, it should be sees
![image](https://github.com/ISIS3510-202320-Team13/Wiki/assets/71995657/f3df4a15-b5dc-4c66-bbb4-2a2684ff8f17)
This persona is necessary?

**Comment by Crola1702** [comment]
Closing because of #11
